Update ImageMetadataExtractor.php
fabarea/metadata pull request #39
Opened 2020-09-20 17:50 UTC by rbinder

Fixes troubles with inserting GPS coordinates when lattitude/longitude aren't present in metadata...

2020-09-21 07:06 UTC, sgrossberndt requested changes
When adding the logic the rationale was that 0.0/0.0 is a valid coordinate in the atlantic ocean and thus not a good default value https://goo.gl/maps/yXxobe5oVuHEqopr7
Instead the latitude/longitude columns should be allowed to be NULLable. But this would require a TYPO3 core change. As long as that is not changed in core this change is ok in general (but should be adapted as commented)

2020-09-21 07:06 UTC, sgrossberndt commented on Classes/Index/ImageMetadataExtractor.php
> +		return ($value === null || $value === '' || $value == 0) ? '0.00000000000000' : (string)$value;
If this is going to be the condition it can be simplified to
`return empty($value) ? '0.00000000000000' : (string)$value;`

also as the method no longer will return NULL the PHPDoc should be adapted too:
`* @return string`

2020-09-21 22:34 UTC, rbinder commented
Sounds good - thank you!

2021-05-11 16:10 UTC, sgrossberndt commented
Replaced by https://github.com/fabarea/metadata/pull/43, can be closed

2021-05-12 15:44 UTC, closed without merging